# Generated by Django 4.0.5 on 2022-07-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupremeCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Location.country')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Embargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embargoed_country', to='Location.country')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('al', 'Ally'), ('nt', 'Neutral'), ('en', 'Enemy')], max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.country')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='Location.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryPresident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Location.country')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='embargos',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver', 'date'), name='unique_embargo'),
        ),
        migrations.AlterUniqueTogether(
            name='countrypresident',
            unique_together={('country', 'president')},
        ),
    ]
