# Generated by Django 4.0.5 on 2022-07-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Weapon', 'Weapon'), ('Food', 'Food'), ('Real Estate', 'Real Estate'), ('Trading', 'Trading'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('raw_material', models.IntegerField(default=0)),
                ('raw_material_price', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon_Company',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Business.company')),
            ],
            bases=('Business.company',),
        ),
        migrations.CreateModel(
            name='ShareHolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Business.company')),
                ('shareholder', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
    ]
