# Generated by Django 4.0.5 on 2022-07-09 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_published', models.DateField(auto_now_add=True)),
                ('date_last_edited', models.DateField(auto_now=True)),
                ('votes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=240)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_newspaper', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('subscribers', models.IntegerField(default=0)),
                ('owners', models.ManyToManyField(related_name='newspapers', to='User.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Media.article')),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='newspaper',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Media.newspaper'),
        ),
    ]
